{% set name = "tappy" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tappy-{{ version }}.tar.gz
  sha256: 76e8c2a855eb0f532cc36e1a134bb3d5795de117f1100b5547e1ffbe3556c4cb

build:
  entry_points:
    - tappy = tappy.tappy:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
  run:
    - python >={{ python_min }}
    - astronomia
    - cltoolbox
    - pyparsing
    - pywavelets
    - skyfield
    - dateparser
    - matplotlib-base >=3.3.2
    - numpy
    - odfpy >=1.4.1
    - openpyxl >=3.0.7
    - pandas
    - pint !=0.21
    - pint-pandas
    - pydantic
    - pytables >=3.6.1
    - pyxlsb >=1.0.8
    - scipy
    - tabulate
    - typing-extensions
    - xlrd >=2.0.1
    - xlsxwriter                                                                 

test:
  imports:
    - tappy
  commands:
    - pip check
    - tappy --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Command line script and Python library perform tidally-based analysis of water level data.
  home: https://pypi.org/project/tappy/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
