{% set name = "tappy" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tappy-{{ version }}.tar.gz
  sha256: 242996b52e39b85b03e803fb84bc6188823ec527b49690c4692574e0e915b132

build:
  entry_points:
    - tappy = tappy.tappy:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7.1
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.7.1
    - toolbox_utils >=5.0.0,<6.0.0
    - astronomia
    - cltoolbox
    - numpy

test:
  imports:
    - tappy
  commands:
    - pip check
    - tappy --help
  requires:
    - pip

about:
  summary: Command line script and Python library perform tidally-based analysis of water level data.
  home: https://pypi.org/project/tappy/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
