{% set name = "tappy" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tappy-{{ version }}.tar.gz
  sha256: e85b789b0a39caf57c955c2b8459bba58b38d9edee64fa82e0b2c09084f13b37

build:
  entry_points:
    - tappy = tappy.tappy:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7.1
    - pip
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
  run:
    - python >=3.7.1
    - astronomia
    - cltoolbox
    - numpy
    - pyparsing
    - scipy
    - toolbox_utils >=5.0.0,<6.0.0

test:
  imports:
    - tappy
  commands:
    - pip check
    - tappy --help
  requires:
    - pip

about:
  summary: Command line script and Python library perform tidally-based analysis of water level data.
  home: https://pypi.org/project/tappy/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
