schema_version: 1

context:
  name: tappy
  version: "1.2.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: bee470d257a3665cc1bc3132a2739abc456eaa7b134921ab41096f95f56d21f1

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps
  python:
    entry_points:
      - tappy = tappy.tappy:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
  run:
    - python >=${{ python_min }}
    - astronomia
    - cltoolbox
    - pyparsing
    - pywavelets
    - skyfield
    - dateparser
    - matplotlib-base >=3.3.2
    - numpy
    - odfpy >=1.4.1
    - openpyxl >=3.0.7
    - pandas
    - pint !=0.21
    - pint-pandas
    - pydantic
    - pytables >=3.6.1
    - pyxlsb >=1.0.8
    - scipy
    - tabulate
    - typing-extensions
    - xlrd >=2.0.1
    - xlsxwriter

tests:
  - python:
      imports:
        - tappy
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - tappy --help

about:
  summary: Command line script and Python library perform tidally-based analysis of water level data.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://pypi.org/project/tappy/

extra:
  recipe-maintainers:
    - timcera
